#### Markov’s Inequality
 Markov’s Inequality provides an upper bound on the probability that a non-negative random
variable is greater than or equal to a certain positive value. It is particularly useful when limited
information is available about the distribution of the variable.

**Example 1**: Website Traffic Analysis

**Problem:** A website has an average of 200 visitors per day. What is the probability that the website
receives 600 or more visitors in a day?

**Solution:**
 Step 1: Identify known values.
 • Mean (expected value) = 200
 • Threshold a = 600

 Step 2: Apply Markov’s Inequality.
 P(X ≥ 600) ≤ E[X]/a
 P(X ≥ 600) ≤ 200/600

 Step 3: Simplify.
 P(X ≥ 600) ≤ 1/3 ≈ 0.333
 Conclusion: The probability that the website gets 600 or more visitors in a day is at most 0.333 or 33.3%.


In [1]:
# Given values
mean_visitors = 200  # Average number of visitors per day
threshold_visitors = 600  # Threshold for the number of visitors

In [2]:

# Apply Markov's Inequality
probability_upper_bound = mean_visitors / threshold_visitors

# Display the result
print(f"The probability that the website gets {threshold_visitors} or more visitors in a day is at most: {probability_upper_bound:.3f}")

The probability that the website gets 600 or more visitors in a day is at most: 0.333


**Example 2:** Quality Control in Manufacturing

**Problem:** A manufacturing plant produces bolts with an average length of 10 cm. What is the probability
that a randomly chosen bolt exceeds 15 cm?

 **Solution:**
 Step 1: Identify known values.
 • Mean (expected value) = 10 cm
 • Threshold a = 15 cm

 Step 2: Apply Markov’s Inequality.
 P(X ≥ 15) ≤ 10/15

 Step 3: Simplify.
 P(X ≥ 15) ≤ 2/3 ≈ 0.667

 **Conclusion:** The probability that a bolt is longer than 15 cm is at most 0.667 or 66.7%.


In [4]:
# Given values
mean_bolt_length = 10  # Average length of bolts in cm
threshold_bolt_length = 15  # Threshold for the bolt length

In [5]:
# Apply Markov's Inequality
probability_upper_bound = mean_bolt_length / threshold_bolt_length

# Display the result
print(f"The probability that a bolt is longer than {threshold_bolt_length} cm is at most: {probability_upper_bound:.3f}")

The probability that a bolt is longer than 15 cm is at most: 0.667


**Example 3:** Customer Spending Analysis

**Problem:** A retail store records average customer spending of ₹500. What is the probability that a
customer spends ₹1500 or more?

**Solution:**
 Step 1: Identify known values.
 • Mean (expected value) = ₹500
 • Threshold a = ₹1500

 Step 2: Apply Markov’s Inequality.
 P(X ≥ 1500) ≤ 500/1500

 Step 3: Simplify.
 P(X ≥ 1500) ≤ 1/3 ≈ 0.333

**Conclusion:** The probability that a customer spends ₹1500 or more is at most 0.333 or 33.3%.


In [6]:
# Given values
mean_spending = 500  # Average customer spending in ₹
threshold_spending = 1500  # Threshold for customer spending

In [7]:
# Apply Markov's Inequality
probability_upper_bound = mean_spending / threshold_spending

# Display the result
print(f"The probability that a customer spends ₹{threshold_spending} or more is at most: {probability_upper_bound:.3f}")

The probability that a customer spends ₹1500 or more is at most: 0.333
